import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame(),
        ]),
      ),
    );
  }
}

class Frame extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1732,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.black),
          child: Stack(
            children: [
              Positioned(
                left: 1,
                top: 491,
                child: Container(
                  width: 1440,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 1440,
                        height: 655,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 43.19,
                              top: 93.16,
                              child: Container(
                                width: 273.30,
                                height: 1,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: -0.19,
                                      top: -0.12,
                                      child: Container(
                                        width: 273,
                                        height: 364,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: Image.network(
                                                "https://via.placeholder.com/273x364"),
                                            fit: BoxFit.contain,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: -0.19,
                                      top: -0.12,
                                      child: Container(width: 273, height: 364),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 384.34,
                              top: 80.19,
                              child: Container(
                                width: 728.17,
                                height: 575,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: -0.34,
                                      top: -1.16,
                                      child: SizedBox(
                                        width: 301,
                                        child: Text(
                                          'Reed Goodman',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 42,
                                            fontFamily: 'Helvetica Neue',
                                            fontWeight: FontWeight.w400,
                                            height: 1.33,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: -0.34,
                                      top: 84.84,
                                      child: SizedBox(
                                        width: 1
